openapi: 3.1.0
info: 
  title: PluralBuddy API
  version: 1.0.2
servers: 
  - url: https://pb.giftedly.dev/api
security: 
  - bearerAuth: 
      []
    apiKeyCookie: 
      []
    oAuth2: 
      []
components: 
  securitySchemes: 
    apiKeyCookie: 
      type: apiKey
      in: cookie
      name: apiKeyCookie
      description: API Key authentication via cookie
    bearerAuth: 
      type: http
      scheme: bearer
      description: Bearer token authentication
    oAuth2: 
      type: oauth2
      description: OAuth 2.1 authentication
      flows: 
        authorizationCode: 
          authorizationUrl: https://pb.giftedly.dev/api/auth/oauth2/authorize
          tokenUrl: https://pb.giftedly.dev/api/auth/oauth2/token
          scopes: 
            profile: Read profile
            openid: Read user ID
            email: Read (fake) user email
            offline_access: Refresh token
            alters:read: Read alter data
            alters:write: Write alter data
            tags:read: Read tag data
            tags:write: Write tag data
            tags:alters: Assign tags to alters
            system:read: Read system data
            system:write: Write to system data
            system:admin: "Read/write to alter, tags & system data."
            system:ai-ap: Create custom auto proxy modes as if this integration was a front tracker.
        clientCredentials: 
          authorizationUrl: https://pb.giftedly.dev/api/auth/oauth2/authorize
          tokenUrl: https://pb.giftedly.dev/api/auth/oauth2/token
          scopes: 
            profile: Read profile
            openid: Read user ID
            email: Read (fake) user email
            offline_access: Refresh token
            alters:read: Read alter data
            alters:write: Write alter data
            tags:read: Read tag data
            tags:write: Write tag data
            tags:alters: Assign tags to alters
            system:read: Read system data
            system:write: Write to system data
            system:admin: "Read/write to alter, tags & system data."
paths: 
  "/v1/users/{user}/alters/{alter}": 
    delete: 
      summary: Delete a system alter
      description: "Delete a system alter by its ID. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - alters:write
    get: 
      summary: Get a system alter
      description: "Get data about a specific alter by ID. `{user}` can be `@me` to target the current OAuth user. This endpoint **does** allow for external system alter data (if achievable in conjunction with the system's privacy settings and the logged in OAuth user)."
      security: 
        - oAuth2: 
            - alters:read
  "/v1/users/{user}/tags/{tag}": 
    delete: 
      summary: Delete a system tag
      description: "Delete a system tag by its ID. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - tags:write
    get: 
      summary: Get a system tag
      description: "Get data about a specific tag by ID. `{user}` can be `@me` to target the current OAuth user. This endpoint **does** allow for external system tag data (if achievable in conjunction with the system's privacy settings and the logged in OAuth user)."
      security: 
        - oAuth2: 
            - tags:read
  "/v1/users/{user}/front": 
    post: 
      summary: Front an alter
      description: "Push an alter to front with [AI/AP](/docs/pluralbuddy/ai-ap)."
      security: 
        - oAuth2: 
            - system:ai-ap
  "/v1/users/{user}/terminology": 
    post: 
      summary: "Modify a user's terminology"
      description: "Modify specific data about a user's terminology. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - system:write
    get: 
      summary: "Get a user's terminology"
      description: "Get specific data about a user's terminology. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - system:read
  /auth/oauth2/token: 
    post: 
      summary: Obtain an OAuth2.1 access token
      security: 
        - bearerAuth: 
            []
  "/v1/users/{user}/alters/{alter}/edit": 
    post: 
      summary: Edit a system alter
      description: "Edit a system alter by its ID. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - alters:write
  "/v1/users/{user}/system/list-alters": 
    get: 
      summary: List system alters
      description: "List data about alters in a system. `{user}` can be `@me` to target the current OAuth user. This endpoint **does** allow for external system tag data (if achievable in conjunction with the system's privacy settings and the logged in OAuth user)."
      security: 
        - oAuth2: 
            - alters:read
  /auth/oauth2/authorize: 
    get: 
      summary: Authorize an OAuth2 request
      security: 
        - bearerAuth: 
            []
  /v1/stats: 
    get: 
      summary: Get PluralBuddy statistics
      security: 
        []
      description: Get data of statistical data related to PluralBuddy.
  "/v1/users/{user}/system/list-tags": 
    get: 
      summary: List system tags
      description: "List data about tags in a system. `{user}` can be `@me` to target the current OAuth user. This endpoint **does** allow for external system tag data (if achievable in conjunction with the system's privacy settings and the logged in OAuth user)."
      security: 
        - oAuth2: 
            - alters:read
  "/v1/users/{user}/tags/{tag}/edit": 
    post: 
      summary: Edit a system tag
      description: "Edit a system tag by its ID. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - tags:write
  /auth/oauth2/revoke: 
    post: 
      summary: Revoke OAuth2 access or refresh token
      security: 
        - bearerAuth: 
            []
  "/v1/users/{user}/system/create-alter": 
    post: 
      summary: Create a system alter
      description: "Create a system alter. `{user}` can be `@me` to target the current OAuth user. Username must be unique."
      security: 
        - oAuth2: 
            - alters:write
  "/v1/users/{user}/system/create-tag": 
    post: 
      summary: Create a system tag
      description: "Create a system tag. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - tags:write
  "/v1/users/{user}/fields/tags/{id}": 
    get: 
      summary: Get a tag by integration field
      description: "Get data about a specific tag by integration field. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - alters:read
  "/v1/users/{user}/fields/alters/{id}": 
    get: 
      summary: Get an alter by integration field
      description: "Get data about a specific alter by integration field. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - alters:read
  /auth/oauth2/introspect: 
    post: 
      summary: Introspect an OAuth2 access or refresh token
      security: 
        - bearerAuth: 
            []
  "/v1/messages/{id}": 
    get: 
      summary: Get PluralBuddy message
      description: Get a PluralBuddy message by Message ID
      security: 
        - oAuth2: 
            []
  "/v1/users/{user}/system/edit": 
    post: 
      summary: Edit system data
      description: "Edit system data. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - system:write
  "/v1/users/{user}/system": 
    get: 
      summary: Get PluralBuddy system
      description: "Get data of a PluralBuddy system. `{user}` can be `@me` to target the current OAuth user."
      security: 
        - oAuth2: 
            - system:read
webhooks: 
  alter.update: 
    post: 
      summary: Receive alter updates
      description: Receive alter updates via Svix Webhooks built into PluralBuddy.
  tag.update: 
    post: 
      summary: Receive tag updates
      description: Receive tag updates via Svix Webhooks built into PluralBuddy.