name: auto-process-openapi
on: push
jobs:
  process-openapi:
    name: Process OpenAPI documentation
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run docs:openapi
      
      # Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          # push the commit back up to source GitHub repository
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
          # stage any file changes to be committed
          git add .
      
          # make commit with staged changes
          git commit -m 'Automatically create OpenAPI documentation from Plurography'
      

          git push
